### ISSUE TITLE
_onResponse is leaking memory

### ISSUE THREAD

**Issue by dbns97** [Conctr/squirrel#10]
The _onResponse table holds callback functions for each agent.send() executed. These are never deleted even after successfully sending and receiving a response. There is also no mechanism for a timeout to clear out expired callbacks or return an error result.

In `_doResponse()`, immediately after `_onResponse[id](response.error, response.body);` add `delete _onResponse[id];`.

The timeout is left for the reader to resolve. Consider adding support for impPager and Bullwinkle.

**Comment by blindman2k** [comment]
This functionality is totally removed now. The latest version of the Conctr class now expects Bullwinkle, impPager or anything similar to handle responses from the agent.
